# Generated by Django 3.1 on 2020-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0003_auto_20200830_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='predicted_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_output', models.ImageField(blank=True, default='default.png', null=True, upload_to='images_output/')),
            ],
        ),
        migrations.RemoveField(
            model_name='face_photos',
            name='img_output',
        ),
    ]
